name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest-16-cores
    steps:
      - uses: actions/checkout@v4

      - uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - run: cog push r8.im/jburnford/olmocr-pdf
